import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { toast } from "sonner";
import { useCreateEvent } from "@/hooks/useEvents";

const EventNew = () => {
  const navigate = useNavigate();
  const createEvent = useCreateEvent();
  const [name, setName] = useState("");
  const [date, setDate] = useState("");
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await createEvent.mutateAsync({
        name,
        slug: "", // auto-generated by trigger
        date,
        description: description || null,
      });
      toast.success("Akce vytvořena!");
      navigate("/admin/events");
    } catch (err: any) {
      toast.error(err.message || "Chyba při vytváření akce");
    } finally {
      setLoading(false);
    }
  };

  const inputClasses =
    "w-full rounded-xl border border-border bg-secondary px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50";

  return (
    <div className="max-w-lg space-y-6">
      <div className="flex items-center gap-3">
        <Link to="/admin/events" className="text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-5 w-5" />
        </Link>
        <h1 className="font-display text-2xl font-bold">Nová akce</h1>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="mb-1.5 block text-sm font-medium">Název akce</label>
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            className={inputClasses}
            placeholder="Maturitní ples 2026"
            required
          />
        </div>
        <div>
          <label className="mb-1.5 block text-sm font-medium">Datum</label>
          <input
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            className={inputClasses}
            required
          />
        </div>
        <div>
          <label className="mb-1.5 block text-sm font-medium">Popis (volitelné)</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className={`${inputClasses} resize-none`}
            rows={3}
            placeholder="Krátký popis akce…"
          />
        </div>
        <button
          type="submit"
          disabled={loading}
          className="w-full rounded-xl gradient-accent py-3 text-sm font-semibold text-primary-foreground shadow-glow transition-transform hover:scale-[1.02] active:scale-95 disabled:opacity-50"
        >
          {loading ? "Vytváření…" : "Vytvořit akci"}
        </button>
      </form>
    </div>
  );
};

export default EventNew;
